### ISSUE TITLE
Bug: incomplete gogo download resumes issue

### ISSUE THREAD

**Issue by ddulz** [SenZmaKi/Senpwai#52]
Pahe have their TLS issue(at least with my connection?), so have to use gogo today, but their download urls seems like always broke after some minutes, so download naturally fail after 2-4 episode.

Issue arise when resuming, sometimes senpcli just download episode 1 rather than resuming next episode.

Edit: extra detail, senpcli does show right episode, but the file actually episode 1.

Thanks.

**Comment by SenZmaKi** [comment]
> Pahe have their TLS issue(at least with my connection?),

Pahe should be working, what exactly does Senpcli output? 

> Edit: extra detail, senpcli does show right episode, but the file actually episode 1.

Are you sure you're experiencing this with gogo cause the downloading of the wrong episode is a problem with pahe but I just fixed it so it should be working fine in the upcoming update

Can you also kindly be more descriptive cause I don't fully understand what you're experiencing, as in describe what you're experiencing as opposed to what you think is happening cause it will help me identify the bug faster. Also if you could send Senpcli's output as an image or just paste it I'd appreciate.

**Comment by ddulz** [comment]
> Pahe should be working, what exactly does Senpcli output?

Turner out to be really my connection problem, you see I live in indonesia, the gov just think that blocking left and right is their job and net neutrality is a myth, here is the output if you want to know, its really problem on my end, i might need vpn i guess....

```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/share/Senpwai/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/data/data/com.termux/files/usr/share/Senpwai/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/data/data/com.termux/files/usr/share/Senpwai/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/share/Senpwai/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/share/Senpwai/.venv/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/share/Senpwai/.venv/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/data/data/com.termux/files/usr/lib/python3.11/ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)
```

> Are you sure you're experiencing this with gogo cause the downloading of the wrong episode is a problem with pahe but I just fixed it so it should be working fine in the upcoming update

Not really sure, with pahe i never have a need to resume with pahe. Thanks to fixing this issue anyways.
 
> Can you also kindly be more descriptive cause I don't fully understand what you're experiencing, as in describe what you're experiencing as opposed to what you think is happening cause it will help me identify the bug faster. Also if you could send Senpcli's output as an image or just paste it I'd appreciate.

Hmm this is what happen senpcli throw when failing to download

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/data/data/com.termux/files/usr/share/Senpwai/senpwai/senpcli/__main__.py", line 4, in <module>
    main()
  File "/data/data/com.termux/files/usr/share/Senpwai/senpwai/senpcli/main.py", line 922, in main
    initiate_download_pipeline(parsed, anime_details)
  File "/data/data/com.termux/files/usr/share/Senpwai/senpwai/senpcli/main.py", line 814, in initiate_download_pipeline
    handle_gogo(parsed, anime_details)
  File "/data/data/com.termux/files/usr/share/Senpwai/senpwai/senpcli/main.py", line 694, in handle_gogo
    download_manager(
  File "/data/data/com.termux/files/usr/share/Senpwai/senpwai/senpcli/main.py", line 525, in download_manager
    pbar, link = create_progress_bar(episode_title, link, is_hls_download)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/share/Senpwai/senpwai/senpcli/main.py", line 456, in create_progress_bar
    episode_size, link_or_segs_urls = Download.get_resource_length(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/share/Senpwai/senpwai/common/scraper.py", line 475, in get_resource_length
    raise NoResourceLengthException(url, redirect_url)
senpwai.common.scraper.NoResourceLengthException: Received no resource length from "https://gredirect.info/download.php?url=aHR0cHM6LyURASDGHUSRFSJGYfdsffsderFStewthsfSFtrfteAawehyfcghysfdsDGDYdgdsfsdfwstdgdsgtertsdf95MjVzbGtuZGwwLmFuZjU5OC5jb20vdXNlcjEzNDIvOGM1ZWY3NTJkMDVkOTVhNzhhZmYxOTY3NDQ0NDIwY2EvRVAuMS52MC4xNjk2NDMxOTA4LjcyMHAubXA0P3Rva2VuPWxfOURrN3lVVHZTS3VoSTdyQUhHb1EmZXhwaXJlcz0xNzIyODQ0MTM3JmlkPTIxMjg4NCZ0aXRsZT0oMTI4MHg3MjAtZ29nb2FuaW1lKWthZ2Utbm8taml0c3VyeW9rdXNoYS1uaS1uYXJpdGFrdXRlLTJuZC1zZWFzb24tZXBpc29kZS0xLm1wNA=="
```

Usually senpcli able to download 2-4 episodes, and then throw that error, so I have to resume with gogo.

**Comment by SenZmaKi** [comment]
Thanks this is good, in the error for gogo that you sent which anime title, quality, sub or dub, episode range were you trying to download, if I can fix this then gogo will be pretty much perfect

**Comment by ddulz** [comment]
That one is eminence in shadow season 2, but yesterday I try with working, so whatever title it still the same.

I use default setting: dub, 720p, and entire episode.

**Comment by SenZmaKi** [comment]
Ok thanks, I've fixed it update should be out in a few
